apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: duy
  labels:
    service: mongo
spec:
  type: ClusterIP
  selector:
    db: mongodb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 27017