apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  namespace: duy
  labels:
    service: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
      nodePort: 30008