apiVersion: v1
kind: Service
metadata:
  name: sidecar-svc
  namespace: duy
  labels:
    service: sidecar
spec:
  type: NodePort
  selector:
    sidecar: nginx-php
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30008