---
apiVersion: v1
kind: Pod                           
metadata:
  name: sidecar
  namespace: duy
  labels:
    sidecar: nginx-php
spec:
  containers:
    - name: sidecar-nginx
      image: minhpq331/demo-sidecar:nginx
      ports:
        - containerPort: 80

    - name: sidecar-php
      image: minhpq331/demo-sidecar:php-fpm
      ports:
        - containerPort: 9000

# kubectl -n duy port-forward --address 0.0.0.0 pod/test 8001:8000